
  CREATE TABLE "CHAT"."CHAT_USER" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CPF" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"IS_ONLINE" CHAR(1 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  
  CREATE SEQUENCE CHAT_USER_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 ORDER;


  
    CREATE TABLE "CHAT"."RESTRICT_WORD" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"WORD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
  
    CREATE SEQUENCE WORD_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 ORDER;

insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Anus');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Baba-ovo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Babaovo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Babaca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bacura');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bagos');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Baitola');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bebum');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Besta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bicha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bisca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bixa');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Boazuda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Boceta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Boco');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Boiola');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bolagato');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Boquete');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bolcat');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bosseta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bosta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bostana');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Brecha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Brexa');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Brioco');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bronha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Buca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Buceta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bunda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Bunduda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Burra');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Burro');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Busseta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cachorra');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cachorro');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cadela');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Caga');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cagado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cagao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cagona');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Canalha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Caralho');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Casseta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cassete');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Checheca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chereca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chibumba');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chibumbo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chifruda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chifrudo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chochota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chupada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Chupado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Clitoris');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cocaina');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Coco');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Corna');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Corno');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cornuda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cornudo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Corrupta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Corrupto');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cretina');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cretino');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cruz-credo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cu');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Culhao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Curalho');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cuzao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cuzuda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Cuzudo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Debil');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Debiloide');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Defunto');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Demonio');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Difunto');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Doida');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Doido');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Egua');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Escrota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Escroto');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Esporrada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Esporrado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Esporro');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Estupida');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Estupidez');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Estupido');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fedida');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fedido');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fedor');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fedorenta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Feia');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Feio');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Feiosa');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Feioso');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Feioza');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Feiozo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Felacao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fenda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Foda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fodao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fode');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'FodidaFodido');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fornica');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fudendo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fudecao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fudida');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Fudido');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Furada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Furado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Furão');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Furnica');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Furnicar');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Furo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Furona');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gaiata');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gaiato');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gay');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gonorrea');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gonorreia');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gosma');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gosmenta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Gosmento');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Grelinho');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Grelo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Homo-sexual');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Homossexual');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Homossexual');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Idiota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Idiotice');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Imbecil');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Iscrota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Iscroto');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Japa');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ladra');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ladrao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ladroeira');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ladrona');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Lalau');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Leprosa');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Leproso');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Lésbica');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Macaca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Macaco');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Machona');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Machorra');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Manguaca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mangua¦a');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Masturba');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Meleca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Merda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mija');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mijada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mijado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mijo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mocrea');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mocreia');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Moleca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Moleque');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mondronga');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Mondrongo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Naba');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Nadega');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Nojeira');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Nojenta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Nojento');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Nojo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Olhota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Otaria');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ot-ria');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Otario');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ot-rio');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Paca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Paspalha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Paspalhao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Paspalho');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pau');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Peia');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Peido');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pemba');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pênis');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pentelha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pentelho');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Perereca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Peru');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pica');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Picao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pilantra');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Piranha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Piroca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Piroco');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Piru');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Porra');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Prega');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Prostibulo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Prost-bulo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Prostituta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Prostituto');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Punheta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Punhetao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pus');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Pustula');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Puta');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Puto');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Puxa-saco');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Puxasaco');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rabao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rabo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rabuda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rabudao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rabudo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rabudona');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Racha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rachada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rachadao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rachadinha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rachadinho');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rachado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ramela');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Remela');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Retardada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Retardado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Ridícula');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rola');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rolinha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Rosca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Sacana');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Safada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Safado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Sapatao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Sifilis');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Siririca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Tarada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Tarado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Testuda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Tezao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Tezuda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Tezudo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Trocha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Trolha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Troucha');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Trouxa');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Troxa');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Vaca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Vagabunda');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Vagabundo');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Vagina');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Veada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Veadao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Veado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Viada');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Víado');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Viadao');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xavasca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xerereca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xexeca');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xibiu');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xibumba');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xochota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xoxota');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xana');
insert into restrict_word (id, word) values (WORD_SEQ.nextval,'Xaninha');